import { jsPDF } from "jspdf";
import { Book, Chapter } from "../types";

export const generatePDF = (book: Book): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  // --- Title Page ---
  if (book.coverImage) {
      try {
          // Cover Image (Centered, nice and big)
          const imgWidth = 120;
          const imgHeight = 160; // 3:4 aspect ratio approx
          const x = (pageWidth - imgWidth) / 2;
          doc.addImage(book.coverImage, 'PNG', x, 40, imgWidth, imgHeight);
          cursorY = 40 + imgHeight + 20;
      } catch (e) {
          console.error("Failed to add cover image to PDF", e);
          cursorY = 80; // Fallback position if image fails
      }
  } else {
      cursorY = pageHeight / 3;
  }

  doc.setFont("times", "bold");
  doc.setFontSize(28);
  
  const titleLines = doc.splitTextToSize(book.title, contentWidth);
  const titleHeight = doc.getTextDimensions(titleLines).h;
  
  doc.text(titleLines, pageWidth / 2, cursorY, { align: "center" });
  cursorY += titleHeight + 20;
  
  doc.setFont("times", "normal");
  doc.setFontSize(14);
  doc.text("Generated by AI Scribe", pageWidth / 2, cursorY, { align: "center" });

  // --- Content Pages ---
  book.chapters.forEach((chapter: Chapter, index: number) => {
    doc.addPage();
    cursorY = margin;

    // Chapter Header with Image
    if (chapter.illustration) {
        try {
            const imgHeight = 60; // Landscape strip
            doc.addImage(chapter.illustration, 'PNG', margin, cursorY, contentWidth, imgHeight);
            cursorY += imgHeight + 15;
        } catch (e) {
            console.error("Failed to add chapter illustration", e);
        }
    }

    // Chapter Title
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.text(`Chapter ${index + 1}`, margin, cursorY);
    cursorY += 10;
    
    doc.setFontSize(18);
    const chTitleLines = doc.splitTextToSize(chapter.title, contentWidth);
    doc.text(chTitleLines, margin, cursorY);
    cursorY += doc.getTextDimensions(chTitleLines).h + 10;

    // Chapter Content
    doc.setFont("times", "normal");
    doc.setFontSize(12);
    
    // Simple markdown cleanup for PDF
    const cleanContent = chapter.content
      .replace(/\*\*(.*?)\*\*/g, '$1') // Bold
      .replace(/\*(.*?)\*/g, '$1')     // Italic
      .replace(/#{1,6}\s/g, '')        // Headers
      .replace(/\n\n/g, '\n');         // Reduce huge gaps

    const lines = doc.splitTextToSize(cleanContent, contentWidth);
    
    const lineHeight = 7;
    
    lines.forEach((line: string) => {
        if (cursorY + lineHeight > pageHeight - margin) {
            doc.addPage();
            cursorY = margin;
        }
        doc.text(line, margin, cursorY);
        cursorY += lineHeight;
    });
  });

  doc.save(`${book.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
};